steps:
  - name: 'sanketbisne/opentofu-docker-image:v4-updated'
    entrypoint: 'bash'
    dir: '/workspace/Running-Remotely' # Adjust the directory based on your project structure
    args: ['-c', 'tofu init']
    
  - name: 'sanketbisne/opentofu-docker-image:v4-updated'
    entrypoint: 'bash'
    dir: '/workspace/Running-Remotely' # Adjust the directory based on your project structure
    args: ['-c', 'tofu plan ']
    
  - name: 'sanketbisne/opentofu-docker-image:v4-updated'
    entrypoint: 'bash'
    dir: '/workspace/Running-Remotely' # Adjust the directory based on your project structure
    args: ['-c', 'tofu apply --auto-approve']

# Optionally, you can specify a timeout for the build
timeout: '1200s' # 20 minutes
