steps:
  - name: 'sanketbisne/opentofu-docker-image:v4-updated'
    entrypoint: 'sh'
    dir: '/Running-Remotely'
    args: ['-c', 'ls' , 'pwd' , 'tofu init']
    

  - name: 'sanketbisne/opentofu-docker-image:v4-updated'
    entrypoint: 'sh'
    dir: '/Running-Remotely'
    args: ['-c', 'tofu plan']
    

  - name: 'sanketbisne/opentofu-docker-image:v4-updated'
    entrypoint: 'sh'
    dir: '/Running-Remotely'
    args: ['-c', 'tofu apply']

# Optionally, you can specify a timeout for the build
timeout: '1200s' # 20 minutes

# If you need to specify environment variables, add them here
# env:
#   - 'ENV_VAR_NAME=value'

# Optionally, you can specify where to store build logs
# logsBucket: 'gs://your-gcs-bucket-name'

# Specify any substitutions (if necessary)
# substitutions:
#   _VARIABLE_NAME:
